### ISSUE TITLE
Still "maintained"?

### ISSUE THREAD

**Issue by nicolasmerino41** [rafaqz/Dispersal.jl#113]
Hey there,

I've been trying to use Dispersal.jl along with DynamicGrids.jl but I'm encountering many incompatibilities/issues (even following the documentation). I believe DynamicGrids is still operable but looks like Dispersal is not? Same for GrowthMaps. Additionally, I've been trying DynamicGrids#dev but that fully disallows the use of Dispersal.jl. 

Other issues, for example: 
Dispersal and GrowthMaps force Rasters.jl to version 0.1.1 which makes it very complicated to work with. 

Additional question (I know it's probably due to DG.jl but didn't have it til I installed Dispersal.jl):
I've started encountering the following error and now I get it all the time. Even running example simulations that used to work for me before, like the Game of Life one:

init = rand(Bool, 150, 200)
output = REPLOutput(init; tspan=1:200, fps=30)
ERROR: MethodError: no method matching _asiterable(::Symbol)
The applicable method may be too new: running in world age 36144, while current world is 37569.

I'd just like to know if there's any intention of updating the whole cesaraustralia package environment or I should move towards a different framework. It has great potential but I find it quite inoperable right now, perhaps it's just my lack of expertise :).

Thank you very much,
Nico

**Comment by rafaqz** [comment]
Thanks for showing interest in the package, part of the reason its not updated is because there are so few issues being made, this is the first in three years.

I do actually actively work on DynamicGrids.jl and use Dispersal.jl models regularly, and do intend to update them (I'm using them both right now on the lastest Rasters.jl). But I'm doing a PhD and overloaded with work, and my other packages that these build on and far more people use and contribute to like DimensionalData.jl and Rasters.jl are getting my priority time.

So, to make things workable here, we need a new breaking release of DynamicGrids.jl and then I can update Dispersal.jl. I cant guarantee when I can get that done by, even the last Rasters.jl release took me a few months.

For now I have pushed a `dev` branch for Dispersal.jl as well so you can do both `] add DynamicGrids#dev` and `] add Dispersal#dev` and you will be using what I am currently using.

**Comment by nicolasmerino41** [comment]
Thank you for the `dev` branch! 

I've been running simple stuff with it and I'm constantly running into the following (new) error when creating any kind of output (ArrayOutput, REPLOutput, GifOutput...):
Display Error: ERROR: UndefVarError: `print_ndims` not defined
I've checked all the documentation and I have no idea what is referring to (I know it's a DG.jl issue more than Dispersal.jl but anyways).

It is quite complicated to develop anything right now if not even example codes work (or it's so hard to pinpoint the origin of the errors). 
I'll stay aware of any new updates and will try to add new issues.

Thank you for the quick response,
Nico

**Comment by rafaqz** [comment]
Ahh thats a DimensionalData.jl thing, sorry. But its only the display, so if you put a ; after the line it will work fine.

Personally I use Makie for all visualisation these days via `MakieOutput`, its much better than the old things I had hacked together .

**Comment by nicolasmerino41** [comment]
Thank you! MakieOutput works so much better! I believe it'd be easier if it could be found in the DG documentation :)

**Comment by rafaqz** [comment]
Feel free to make a PR with nice docs for MakieOutput then ;)

You can base them on another Output doc.
